In [3]:
import numpy as np

X = np.random.randint(2, size = (40,10))
Y = np.zeros((40,1), dtype=int)
for i in range(40):
  Y[i] = np.sum(X[i])
x_train = X[0:30]
x_test = X[30:40]

print("==========X=============")
print(X)
print("==========Y=============")
print(Y)
print("==========x_train=======")
print(x_train)
print("==========x_test=======")
print(x_test)
y_train = Y[0:30]
y_test = Y[30:40]
print("==========y_train=======")
print(y_train)
print("==========y_test=======")
print(y_test)

==========X=============
[[1 0 0 0 0 1 0 1 0 0]
 [0 1 1 0 0 0 1 1 1 1]
 [1 1 0 0 0 0 1 0 1 0]
 [1 0 0 0 0 1 1 1 1 0]
 [0 1 0 1 0 1 1 1 0 0]
 [1 1 0 1 0 1 1 1 0 1]
 [0 0 0 0 0 0 1 1 1 0]
 [0 0 1 0 1 0 1 1 0 0]
 [1 1 1 1 1 1 0 0 1 1]
 [1 0 1 0 0 1 0 0 0 1]
 [0 0 1 0 0 1 0 1 0 0]
 [0 1 1 1 0 0 1 1 0 0]
 [1 1 0 0 1 1 1 0 0 1]
 [0 0 0 1 1 0 1 0 0 0]
 [0 1 1 1 0 0 1 0 0 1]
 [0 1 0 0 0 0 0 0 1 1]
 [0 1 1 0 1 1 0 1 1 0]
 [1 1 0 0 0 1 0 0 1 0]
 [1 0 1 1 0 1 0 0 1 0]
 [1 1 1 0 1 1 1 1 0 1]
 [1 0 0 1 1 1 1 0 1 0]
 [0 1 1 1 1 1 1 0 1 0]
 [0 1 1 1 1 0 0 0 1 0]
 [0 1 0 0 1 0 0 0 0 0]
 [1 1 1 1 1 0 1 1 1 0]
 [1 1 0 1 1 1 1 0 1 1]
 [1 1 0 0 1 1 1 1 1 0]
 [1 0 0 0 1 1 1 1 1 0]
 [0 1 0 1 0 0 1 0 0 0]
 [1 1 1 1 0 1 0 0 0 0]
 [0 0 1 1 1 1 0 1 1 0]
 [0 1 0 0 1 1 0 0 1 1]
 [1 1 0 0 1 0 0 1 0 0]
 [1 1 1 0 1 1 0 1 0 0]
 [1 0 1 0 0 0 0 0 1 0]
 [1 1 0 1 1 0 0 1 0 1]
 [0 1 1 0 1 0 1 0 1 0]
 [1 1 0 1 0 1 1 1 1 0]
 [1 1 1 0 0 0 0 1 0 1]
 [1 1 0 0 1 1 0 1 0 0]]
==========Y=============
[[3]
 [6]
 [4]
 [5]
 [5]
 [7]

In [27]:
from random import random
import numpy as np
import math as m

# Elman Recurrent Neural Network
class RNN:

    def __init__(self, x_train, x_test, y_train, y_test):
        
        self.I = 30 # Nombre de séquences 
        self.T = 8 # Nb de bits 

        self.x_train = x_train
        self.x_test = x_test
        self.y_train = y_train
        self.y_test = y_test

        # learning rates
        self.alpha1 = 0.01 
        self.alpha2 = 0.01

        # weights
        self.Vx = random()
        self.Vf = random()

    def forward_prop(self, y_pred, Ft):
      sommeF = 0
      for i in range(self.I):
          for t in range(self.T):
              if (t == 0):
                  Ft[i][t] = self.Vx * X[i][t]
                  sommeF += Ft[i][t]
              else :
                  Ft[i][t] = self.Vf * Ft[i][t-1] + self.Vx * X[i][t]
                  sommeF += Ft[i][t]
          y_pred[i] = sommeF
      return y_pred, Ft

    #Back Propagation
    def backward_prop(self):
      y_pred = np.zeros(self.I)
      Ft = np.zeros((self.I,self.T))
      grad_Vx = 0
      grad_Vf = 0
      conv = 1

      epoch = 0
      while (epoch < 100):
          #1st step : forward_prop    
          y_pred, Ft = self.forward_prop(y_pred, Ft)

          #2nd step : backward_prop      
          Vx_back = self.Vx
          Vf_back = self.Vf    
          for i in range(self.I):
              for t in range(self.T):
                  # dE/dVx
                  grad_Vx += (y_pred[i] - self.y_train[i]) * X[i][t] * np.power(self.Vf,(self.T - t))
                  # dE/dVf
                  grad_Vf += (y_pred[i] - self.y_train[i]) * Ft[i][t] * np.power(self.Vf,(self.T - t))
          self.Vx -= self.alpha1 * grad_Vx
          self.Vf -= self.alpha2 * grad_Vf

          epoch+=1
      conv = abs(self.Vx - Vx_back) + abs(self.Vf - Vf_back)   
      #print("Y PRED: \n",y_pred)
      return y_pred, conv

    def backward_prop_results(self):
      y_pred,conv = self.backward_prop()
      print("y_train: ", self.y_train) 
      print("y_pred: ", y_pred)
      print("(y_train - y_pred): ", self.y_train-y_pred)

    def resilient_prop(self, y_train, dX=0.001, df=0.001, np=1.2, nn=.5):
        grad_Vx = 0
        grad_Vf = 0
        conv = 1

        epoch = 0
        while(epoch<100):
            #1st step : forward_prop
            y_pred, Ft = self.forward_prop(y_pred, Ft)
              
            #2nd step : resilient_prop
            Vx_back = self.Vx
            Vf_back = self.Vf 

            for i in range(self.I):
                for t in range(self.T):
                    # dE/dVx
                    grad_Vx += (y_pred[i] - self.y_train[i]) * X[i][t] * np.power(self.Vf,(self.T - t))
                    # dE/dVf
                    grad_Vf += (y_pred[i] - self.y_train[i]) * Ft[i][t] * np.power(self.Vf,(self.T - t))

            #Vx_itera
            dirVx =  Vx_back * grad_Vx
            ampVx =  dX 
            if dirVx * ampVx >= 0 :
                dX *= np
            else:
                dX *= nn
            self.Vx -= self.Vx - m.copysign(dX, grad_Vx)

            #Vf_itera
            dirVf =  Vf_back * grad_Vf
            ampVf =  df 
            if dirVf * ampVf >= 0 :
                df *= np
            else:
                df *= nn
            self.Vf = self.Vf - m.copysign(df, grad_Vf)
            
            epoch +=1 
        conv = abs(self.Vx - Vx_back) + abs(self.Vf - Vf_back)
        return y_pred, conv

    def resilient_prop_results(self):        
      y_pred,conv = self.resilient_prop()
      print("y_train: ", self.y_train) 
      print("y_pred: ", y_pred)
      print("(y_train - y_pred): ", self.y_train-y_pred)



In [28]:
recurrent_network = RNN(x_train, x_test, y_train, y_test)
print("-------Backward Propagation------")
recurrent_network.backward_prop_results()
print("-------Resilient Propagation------")
recurrent_network.resilient_prop_results()

-------Backward Propagation------
y_train:  [[3]
 [6]
 [4]
 [5]
 [5]
 [7]
 [3]
 [4]
 [8]
 [4]
 [3]
 [5]
 [6]
 [3]
 [5]
 [3]
 [6]
 [4]
 [5]
 [8]
 [6]
 [7]
 [5]
 [2]
 [8]
 [8]
 [7]
 [6]
 [3]
 [5]]
y_pred:  [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan]
(y_train - y_pred):  [[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
  nan nan nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan n

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:58: RuntimeWarning: overflow encountered in multiply
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:60: RuntimeWarning: overflow encountered in multiply
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:34: RuntimeWarning: invalid value encountered in multiply
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in multiply
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:34: RuntimeWarning: invalid value encountered in add


NameError: ignored